name: concurrency-false

on: 
  workflow_dispatch:
  # schedule: 
  #  - cron: "*/1 * * * *"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Welcome message
        run: echo " Good Morning"

  Deploy:
    needs: docker
    concurrency:
      group: production-deployment
      cancel-in-progress: false
    runs-on: ubuntu-latest

    steps:
      - name: Welcome message
        run: echo " Good evening"

      - name: sleep
        run: sleep 120
    


      