name: event-triggers

on: 
  workflow_dispatch:
  # schedule: 
  #  - cron: "*/1 * * * *"

jobs:
  event_job:
    runs-on: ubuntu-latest

    steps:
      - name: Welcome message
        run: echo " Good Morning"