name: matix

on: push

jobs:
  docker-deploy:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - images: alpine
            os: windows-latest
        include:
          - images: amd64/alpine
            os: ubuntu-latest
            
    runs-on: ${{ matrix.os }}
    steps:
    - name: docker details
      run: docker info
  
    - name: run the docker image
      run: docker run ${{ matrix.images }}

  


