name: Generate ASCII Artwork

on : push

jobs:
  ascii_job: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    
    - name: List repo files
      run: ls -lrta

    - name: Executing the shell script
      run: ./askii-shell-script.sh